#ifndef __XCINDEX_HELP_H__
#define __XCINDEX_HELP_H__

static const char kToolHelp[] =
    "Utility to test the build system APIs that the index service interacts with.\n"
    "\n"
    "DISCLAIMER: This is intended to be used for diagnostic purposes only.\n"
    "The specific options and provided functionality may change at any point. The tool may be renamed or removed in the future.\n"
    "\n"
    "Usage: xcindex-test [options] [-- <console command> [-- <console command>]...]\n"
    "\n"
    "After executing commands (if any are provided from command-line) the tool enters REPL mode.\n"
    "\n"
    "Options:\n"
    "    -project <path>\n"
    "        path to Xcode project or workspace file\n"
    "    -debugActivityLog\n"
    "        enable XCBuild's debug activity log (default: false)\n"
    "    -derivedDataPath <path>\n"
    "        path to use for derived-data directory\n"
    "    -continue-after-errors\n"
    "        continue actions even if there is an error\n"
    "\n"
    "Console command: <action> [options]\n"
    "\n"
    "Actions (must specify one):\n"
    "    help\n"
    "        print help message\n"
    "    quit\n"
    "        quit REPL mode\n"
    "    beep\n"
    "        make a sound\n"
    "    prepare\n"
    "        do a modern 'prepare-for-index' using a set of targets. If no '-target' is passed then all are included\n"
    "    create-build-description\n"
    "        create build description\n"
    "    print-build-description\n"
    "        print build description ID\n"
    "    print-build-description-targets\n"
    "        print the targets covered by the build description\n"
    "    print-destination\n"
    "        print the currently selected run destination\n"
    "    print-stats\n"
    "        print statistics about targets\n"
    "    list-indexables\n"
    "        print information for indexable targets\n"
    "    list-schemes\n"
    "        print scheme names\n"
    "    print-index-build-settings\n"
    "        print all the indexable build settings as JSON\n"
    "    index-files\n"
    "        test the index compiler invocations for the indexable files\n"
    "\n"
    "Options:\n"
    "    -destination <specifier>\n"
    "        run destination specifier\n"
    "    -scheme <name>\n"
    "        name of the scheme to use\n"
    "    -target <name> [-target <name> ..]\n"
    "        name of the target to use\n"
    "    -targets-of-scheme <name>\n"
    "        select the targets of a scheme\n"
    "    -targets-not-of-scheme <name>\n"
    "        select all the targets not part of a scheme\n"
    "    -all-targets\n"
    "        select all the targets in the workspace\n"
    "    -ignore-list-path\n"
    "        path to new-line-separated list of targets to ignore\n"
    "    -skip-first-n <integer>\n"
    "        skip processing for the first <N> targets\n"
    "    -build-description <string>\n"
    "        build description ID to use\n"
    "    -file <name>\n"
    "        name of the file to index or get settings for\n"
    "    -output-path-only\n"
    "        for build settings only get the output path files\n"
    "    -use-build-manager\n"
    "        get settings using the index build manager\n"
    "    -prepare-dependencies\n"
    "        prepares build dependencies as part of querying for index build settings or indexing files\n"
    "    -high-priority\n"
    "        query index build settings as high priority\n"
    "    -configuration <name>\n"
    "        configuration name to use (default: \"Debug\")\n"
    "    -qos <name>\n"
    "        QoS to use for the build operation (default: 'default')\n"
    "    -j <integer>\n"
    "        max number of parallel jobs (default: processor count)\n"
    "    -v\n"
    "        verbose output\n"
    "    -quiet\n"
    "        avoid printing command results, so that printing is not measured for timing output\n"
    ;

static const char kConsoleHelp[] =
    "Console command: <action> [options]\n"
    "\n"
    "Actions (must specify one):\n"
    "    help\n"
    "        print help message\n"
    "    quit\n"
    "        quit REPL mode\n"
    "    beep\n"
    "        make a sound\n"
    "    prepare\n"
    "        do a modern 'prepare-for-index' using a set of targets. If no '-target' is passed then all are included\n"
    "    create-build-description\n"
    "        create build description\n"
    "    print-build-description\n"
    "        print build description ID\n"
    "    print-build-description-targets\n"
    "        print the targets covered by the build description\n"
    "    print-destination\n"
    "        print the currently selected run destination\n"
    "    print-stats\n"
    "        print statistics about targets\n"
    "    list-indexables\n"
    "        print information for indexable targets\n"
    "    list-schemes\n"
    "        print scheme names\n"
    "    print-index-build-settings\n"
    "        print all the indexable build settings as JSON\n"
    "    index-files\n"
    "        test the index compiler invocations for the indexable files\n"
    "\n"
    "Options:\n"
    "    -destination <specifier>\n"
    "        run destination specifier\n"
    "    -scheme <name>\n"
    "        name of the scheme to use\n"
    "    -target <name> [-target <name> ..]\n"
    "        name of the target to use\n"
    "    -targets-of-scheme <name>\n"
    "        select the targets of a scheme\n"
    "    -targets-not-of-scheme <name>\n"
    "        select all the targets not part of a scheme\n"
    "    -all-targets\n"
    "        select all the targets in the workspace\n"
    "    -ignore-list-path\n"
    "        path to new-line-separated list of targets to ignore\n"
    "    -skip-first-n <integer>\n"
    "        skip processing for the first <N> targets\n"
    "    -build-description <string>\n"
    "        build description ID to use\n"
    "    -file <name>\n"
    "        name of the file to index or get settings for\n"
    "    -output-path-only\n"
    "        for build settings only get the output path files\n"
    "    -use-build-manager\n"
    "        get settings using the index build manager\n"
    "    -prepare-dependencies\n"
    "        prepares build dependencies as part of querying for index build settings or indexing files\n"
    "    -high-priority\n"
    "        query index build settings as high priority\n"
    "    -configuration <name>\n"
    "        configuration name to use (default: \"Debug\")\n"
    "    -qos <name>\n"
    "        QoS to use for the build operation (default: 'default')\n"
    "    -j <integer>\n"
    "        max number of parallel jobs (default: processor count)\n"
    "    -v\n"
    "        verbose output\n"
    "    -quiet\n"
    "        avoid printing command results, so that printing is not measured for timing output\n"
    ;

#endif /* __XCINDEX_HELP_H__ */
